/**
 * Generate 81x81 PNG tabbar icons without external dependencies.
 * Produces solid-color pixel glyphs from a hand-drawn 81x81 bitmask.
 */
const fs = require('fs');
const path = require('path');
const zlib = require('zlib');

// 81x81 pixel art icons, encoded as strings of 0/1
const ICONS = {
  home: `
............................HHHH............................
..........................HHHHHHHH..........................
........................HHHHHHHHHHHH........................
......................HHHHHHHHHHHHHHHH......................
....................HHHHHHHHHHHHHHHHHHHH....................
..................HHHHHHHHHHHHHHHHHHHHHHHH..................
................HHHHHHHHHHHHHHHHHHHHHHHHHHHH................
..............HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH..............
............HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH............
..........HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH..........
........HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH........
......HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH......
....HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH....
..HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH..
.HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.
............................................HHHHHHHHHHHHHH..
............................................HHHHHHHHHHHHHH..
............................................HHHHHHHHHHHHHH..
............................................HHHHHHHHHHHHHH..
............................................HHHHHHHHHHHHHH..
............................................HHHHHHHHHHHHHH..
............................................HHHHHHHHHHHHHH..
............................................HHHHHHHHHHHHHH..
............................................HHHHHHHHHHHHHH..
............................................HHHHHHHHHHHHHH..
............................................HHHHHHHHHHHHHH..
............................................HHHHHHHHHHHHHH..
............................................HHHHHHHHHHHHHH..
............................................HHHHHHHHHHHHHH..
............................................HHHHHHHHHHHHHH..
............................................HHHHHHHHHHHHHH..
............................................HHHHHHHHHHHHHH..
............................................HHHHHHHHHHHHHH..
............................................HHHHHHHHHHHHHH..
............................................HHHHHHHHHHHHHH..
............................................HHHHHHHHHHHHHH..
............................................HHHHHHHHHHHHHH..
`,
  workhours: `
.................................................................................
....................................HHHHHHHH......................................
..................................HHHHHHHHHHHH....................................
..................................HH........HH....................................
..................................HH........HH....................................
..................................HH........HH....................................
..................................HH........HH....................................
..................................HH........HH....................................
..................................HH........HH....................................
..................................HH........HH....................................
..................................HH........HH....................................
..................................HH........HH....................................
..................................HH........HH....................................
..................................HH........HH....................................
..................................HH........HH....................................
..................................HH........HH....................................
..................................HH........HH....................................
..................................HH........HH....................................
..................................HH........HH....................................
..................................HH........HH....................................
..................................HH........HH....................................
..................................HH........HH....................................
..................................HH........HH....................................
..................................HH........HH....................................
..................................HHHHHHHHHHHH....................................
....................................HHHHHHHH......................................
.................................................................................
`,
  salary: `
.................................................................................
..................................HHHHHHHHHHHH....................................
..................................HHHHHHHHHHHH....................................
..................................HHHHHHHHHHHH....................................
..................................HH........HH....................................
..................................HH........HH....................................
..................................HHHHHHHHHHHH....................................
..................................HHHHHHHHHHHH....................................
..................................HH........HH....................................
..................................HH........HH....................................
..................................HH........HH....................................
..................................HH........HH....................................
..................................HH........HH....................................
..................................HH........HH....................................
..................................HH........HH....................................
..................................HH........HH....................................
..................................HH........HH....................................
..................................HHHHHHHHHHHH....................................
..................................HHHHHHHHHHHH....................................
`,
  community: `
.................................................................................
......................HHHH............................HHHH......................
....................HHHHHHHH........................HHHHHHHH....................
..................HHHHHHHHHHHH....................HHHHHHHHHHHH..................
................HHHHHHHHHHHHHHHH................HHHHHHHHHHHHHHHH..............
..............HHHHHHHHHHHHHHHHHHHH........HHHHHHHHHHHHHHHHHHHH..............
............HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH............
..........HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH..........
........HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH........
........HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH........
..........HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH..........
............HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH............
..............HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH..............
................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH..............
..................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH..................
....................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH....................
......................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH......................
........................HHHHHHHHHHHHHHHHHHHHHHHHHHHH........................
..........................HHHHHHHHHHHHHHHHHHHHHH..........................
............................HHHHHHHHHHHHHHHH............................
..............................HHHHHHHHHHHH..............................
................................HHHHHHHH............................
..................HHHH............................HHHH......................
................HHHHHHHH........................HHHHHHHH....................
..............HHHHHHHHHHHH....................HHHHHHHHHHHH..................
............HHHHHHHHHHHHHHHH................HHHHHHHHHHHHHHHH..............
..........HHHHHHHHHHHHHHHHHHHH........HHHHHHHHHHHHHHHHHHHH..............
........HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH........
..........HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH........
............HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH............
..............HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH..............
................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH..............
..................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH..................
....................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH....................
......................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH......................
........................HHHHHHHHHHHHHHHHHHHHHHHHHHHH........................
..........................HHHHHHHHHHHHHHHHHHHHHH..........................
............................HHHHHHHHHHHHHHHH............................
..............................HHHHHHHHHHHH..............................
................................HHHHHHHH............................
`,
  profile: `
.................................................................................
......................................HHHHHHHH....................................
....................................HHHHHHHHHHHH..................................
..................................HHHHHHHHHHHHHHHH................................
..................................HHHHHHHHHHHHHHHH................................
..................................HHHHHHHHHHHHHHHH................................
..................................HHHHHHHHHHHHHHHH................................
....................................HHHHHHHHHHHH..................................
......................................HHHHHHHH....................................
`,
  profileBody: `
.................................................................................
.................................................................................
.................................................................................
.................................................................................
.................................................................................
.................................................................................
.................................................................................
.................................................................................
............................HHHHHHHHHHHHHHHHHHHHHH................................
..........................HHHHHHHHHHHHHHHHHHHHHHHHHHHH............................
........................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH..........................
......................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH........................
....................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH......................
..................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH..................
................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH................
..............HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH............
............HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH............
..........HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH..........
........HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH........
........HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH........
..........HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH..........
............HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH............
..............HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH..............
................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH................
..................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH..................
....................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH......................
......................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH........................
........................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH..........................
..........................HHHHHHHHHHHHHHHHHHHHHHHHHHHH............................
............................HHHHHHHHHHHHHHHHHHHHHH................................
`
};

// Parse icon string to 81x81 boolean matrix
function parseIcon(str) {
  const lines = str.split('\n').filter(l => l.length > 0);
  const grid = [];
  for (let y = 0; y < 81; y++) {
    const line = lines[y] || '';
    const row = [];
    for (let x = 0; x < 81; x++) {
      row.push(line.charAt(x) === 'H');
    }
    grid.push(row);
  }
  return grid;
}

// Compose multiple icons (e.g., profile = head + body)
function composeIcons(...icons) {
  const grids = icons.map(parseIcon);
  const result = [];
  for (let y = 0; y < 81; y++) {
    const row = [];
    for (let x = 0; x < 81; x++) {
      row.push(grids.some(g => g[y] && g[y][x]));
    }
    result.push(row);
  }
  return result;
}

// Build PNG from 81x81 boolean grid, drawing pixels as color
function buildPng(grid, color) {
  // RGBA: 4 bytes per pixel, 81 pixels per row, 81 rows
  const width = 81;
  const height = 81;
  const bpp = 4;
  const rowSize = width * bpp;
  const raw = Buffer.alloc((rowSize + 1) * height);

  // Parse hex color (#RRGGBB) to RGB bytes
  const hex = color.replace('#', '');
  const r = parseInt(hex.substring(0, 2), 16);
  const g = parseInt(hex.substring(2, 4), 16);
  const b = parseInt(hex.substring(4, 6), 16);

  for (let y = 0; y < height; y++) {
    raw[y * (rowSize + 1)] = 0; // filter byte: None
    for (let x = 0; x < width; x++) {
      const offset = y * (rowSize + 1) + 1 + x * bpp;
      const isOn = grid[y] && grid[y][x];
      if (isOn) {
        raw[offset] = r;
        raw[offset + 1] = g;
        raw[offset + 2] = b;
        raw[offset + 3] = 255; // alpha
      } else {
        raw[offset] = 0;
        raw[offset + 1] = 0;
        raw[offset + 2] = 0;
        raw[offset + 3] = 0; // transparent
      }
    }
  }

  const compressed = zlib.deflateSync(raw);

  // PNG signature
  const signature = Buffer.from([0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A]);

  // IHDR chunk
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(width, 0);
  ihdr.writeUInt32BE(height, 4);
  ihdr[8] = 8; // bit depth
  ihdr[9] = 6; // color type: RGBA
  ihdr[10] = 0; // compression
  ihdr[11] = 0; // filter
  ihdr[12] = 0; // interlace

  return Buffer.concat([
    signature,
    makeChunk('IHDR', ihdr),
    makeChunk('IDAT', compressed),
    makeChunk('IEND', Buffer.alloc(0))
  ]);
}

function makeChunk(type, data) {
  const length = Buffer.alloc(4);
  length.writeUInt32BE(data.length, 0);
  const typeBuf = Buffer.from(type, 'ascii');
  const crc = crc32(Buffer.concat([typeBuf, data]));
  const crcBuf = Buffer.alloc(4);
  crcBuf.writeUInt32BE(crc >>> 0, 0);
  return Buffer.concat([length, typeBuf, data, crcBuf]);
}

// CRC32 for PNG chunks
const crcTable = (function() {
  const table = new Uint32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) {
      c = (c & 1) ? (0xEDB88320 ^ (c >>> 1)) : (c >>> 1);
    }
    table[n] = c >>> 0;
  }
  return table;
})();

function crc32(buf) {
  let crc = 0xFFFFFFFF;
  for (let i = 0; i < buf.length; i++) {
    crc = crcTable[(crc ^ buf[i]) & 0xFF] ^ (crc >>> 8);
  }
  return (crc ^ 0xFFFFFFFF) >>> 0;
}

// Output directory
const outDir = path.join(__dirname, 'images', 'tabbar');
fs.mkdirSync(outDir, { recursive: true });

// Generate all icons in two colors
const configs = [
  { name: 'home', grid: parseIcon(ICONS.home) },
  { name: 'workhours', grid: parseIcon(ICONS.workhours) },
  { name: 'salary', grid: parseIcon(ICONS.salary) },
  { name: 'community', grid: parseIcon(ICONS.community) },
  { name: 'profile', grid: composeIcons(ICONS.profile, ICONS.profileBody) }
];

const INACTIVE = '#999999';
const ACTIVE = '#2864AC';

const generated = [];
for (const cfg of configs) {
  const inactivePng = buildPng(cfg.grid, INACTIVE);
  const activePng = buildPng(cfg.grid, ACTIVE);
  fs.writeFileSync(path.join(outDir, cfg.name + '.png'), inactivePng);
  fs.writeFileSync(path.join(outDir, cfg.name + '-active.png'), activePng);
  generated.push(cfg.name + '.png', cfg.name + '-active.png');
}

console.log('Generated ' + generated.length + ' icons:');
generated.forEach(f => console.log(' - ' + f));
